name: Vinyasa Power
favicon: null
layout_spectrum: 0.016144368099048734
typography_spectrum: 0.3442156547680497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f3f5'
    - '#1e1413'
    - '#4e3342'
    - '#a08399'
    - '#cfbec6'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
